# Generated by Django 5.1.2 on 2024-10-28 07:16

import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Hotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("image", models.FileField(upload_to="hotel_gallery/")),
                ("address", models.CharField(max_length=200)),
                ("mobile", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Draft", "Draft"),
                            ("Disabled", "Disabled"),
                            ("Rejected", "Rejected"),
                            ("In Review", "In Review"),
                            ("Live", "Live"),
                        ],
                        default="Live",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        help_text="Separate tags with commas", max_length=200
                    ),
                ),
                ("views", models.IntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                (
                    "hid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz",
                        length=10,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
