# Generated by Django 5.1.2 on 2024-10-28 09:47

import django.db.models.deletion
import shortuuid.django_fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hotel", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotel",
            name="image",
            field=models.ImageField(upload_to="hotel_gallery/"),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("paid", "Paid"),
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("cancelled", "Cancelled"),
                            ("initiated", "Initiated"),
                            ("failed", "Failed"),
                            ("refunding", "Refunding"),
                            ("refunded", "Refunded"),
                            ("unpaid", "Unpaid"),
                            ("expired", "Expired"),
                        ],
                        max_length=100,
                    ),
                ),
                ("full_name", models.CharField(max_length=1000)),
                ("email", models.EmailField(max_length=1000)),
                ("phone", models.CharField(max_length=1000)),
                (
                    "before_discount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("check_in_date", models.DateField()),
                ("check_out_date", models.DateField()),
                (
                    "saved",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("checked_in_tracker", models.BooleanField(default=False)),
                ("checked_out_tracker", models.BooleanField(default=False)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "stripe_payment_intent",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "success_id",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "booking_id",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet=None, length=10, max_length=20, prefix="", unique=True
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hotel.hotel",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("guest_out", models.DateTimeField()),
                ("guest_in", models.DateTimeField()),
                ("description", models.TextField(blank=True, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.booking"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelFAQs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=1000)),
                ("answer", models.CharField(blank=True, max_length=1000, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hotel FAQs",
            },
        ),
        migrations.CreateModel(
            name="HotelFeatures",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "icon_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Bootstrap Icons", "Bootstrap Icons"),
                            ("Fontawesome Icons", "Fontawesome Icons"),
                            ("Box Icons", "Box Icons"),
                            ("Remi Icons", "Remi Icons"),
                            ("Flat Icons", "Flat Icons"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
                ("icon", models.CharField(blank=True, max_length=100, null=True)),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hotel Features",
            },
        ),
        migrations.CreateModel(
            name="HotelGallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="hotel_gallery/")),
                (
                    "hgid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz",
                        length=10,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Hotel Gallery",
            },
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("room_number", models.CharField(max_length=1000)),
                ("is_available", models.BooleanField(default=True)),
                (
                    "rid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz",
                        length=10,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Rooms",
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ManyToManyField(to="hotel.room"),
        ),
        migrations.CreateModel(
            name="RoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("number_of_beds", models.PositiveIntegerField(default=0)),
                ("room_capacity", models.PositiveIntegerField(default=0)),
                (
                    "rtid",
                    shortuuid.django_fields.ShortUUIDField(
                        alphabet="abcdefghijklmnopqrstuvwxyz",
                        length=10,
                        max_length=20,
                        prefix="",
                        unique=True,
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "hotel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.hotel"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="room",
            name="room_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="hotel.roomtype"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hotel.roomtype",
            ),
        ),
        migrations.CreateModel(
            name="StaffOnDuty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("staff_id", models.CharField(blank=True, max_length=190, null=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hotel.booking"
                    ),
                ),
            ],
        ),
    ]
