# Generated by Django 3.2.22 on 2024-10-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_bookmark_coupon_notification_roomservices'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='num_adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='num_children',
            field=models.IntegerField(default=0),
        ),
    ]
